name: Build Check

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  windows-debug:
    name: Windows x64 Debug (with Tests)
    runs-on: windows-latest

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Copy Auxiliary Files
        run: |
          mkdir "${{ github.workspace }}\dist"
          copy "${{ github.workspace }}\scripts\steam_appid.txt" "${{ github.workspace }}\dist\"
          copy "${{ github.workspace }}\lib\windows\*.dll" "${{ github.workspace }}\dist\"
          copy "${{ github.workspace }}\scripts\windows\xsbinit.config" "${{ github.workspace }}\dist\"

      - name: Configure CMake
        run: cmake -G "Visual Studio 17 2022" -A "X64" -S "${{ github.workspace }}/source" -B "${{ github.workspace }}/cmake-build" -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/dist" -DCMAKE_TOOLCHAIN_FILE="${Env:VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreadedDebugDLL" -DCMAKE_VERBOSE_MAKEFILE=YES -DBUILD_TESTING=YES -DSTAR_USE_JEMALLOC=OFF -DSTAR_BUILD_QT_TOOLS=OFF -DSTAR_ENABLE_STEAM_INTEGRATION=ON -DSTAR_ENABLE_DISCORD_INTEGRATION=ON -DCMAKE_INCLUDE_PATH="${{ github.workspace }}\lib\windows\include" -DCMAKE_LIBRARY_PATH="${{ github.workspace }}\lib\windows"

      - name: Build Debug
        run: cmake --build "${{ github.workspace }}/cmake-build" --config "Debug" --parallel

      - name: Run Unit Tests
        run: ctest --test-dir "${{ github.workspace }}/cmake-build" --verbose --build-config "Debug"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64-debug
          path: dist/*

  windows-release:
    name: Windows x64 Release
    runs-on: windows-latest

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Copy Auxiliary Files
        run: |
          mkdir "${{ github.workspace }}\dist"
          copy "${{ github.workspace }}\scripts\steam_appid.txt" "${{ github.workspace }}\dist\"
          copy "${{ github.workspace }}\lib\windows\*.dll" "${{ github.workspace }}\dist\"
          copy "${{ github.workspace }}\scripts\windows\xsbinit.config" "${{ github.workspace }}\dist\"

      - name: Configure CMake
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
        run: cmake -G "Visual Studio 17 2022" -A "X64" -S "${{ github.workspace }}/source" -B "${{ github.workspace }}/cmake-build" -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/dist" -DCMAKE_TOOLCHAIN_FILE="${Env:VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreadedDLL" -DCMAKE_VERBOSE_MAKEFILE=YES -DSTAR_USE_JEMALLOC=OFF -DSTAR_BUILD_QT_TOOLS=OFF -DSTAR_ENABLE_STEAM_INTEGRATION=ON -DSTAR_ENABLE_DISCORD_INTEGRATION=ON -DCMAKE_INCLUDE_PATH="${{ github.workspace }}\lib\windows\include" -DCMAKE_LIBRARY_PATH="${{ github.workspace }}\lib\windows"

      - name: Build Release
        run: cmake --build "${{ github.workspace }}/cmake-build" --config "Release" --parallel

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64-release
          path: dist/*

  linux-debug:
    name: Linux x86_64 Debug (with Tests)
    runs-on: ubuntu-latest

    steps:
      - name: Install Build Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev ninja-build

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Copy Auxiliary Files
        run: |
          mkdir "${{ github.workspace }}/dist"
          cp "${{ github.workspace }}/lib/linux/libsteam_api.so" "${{ github.workspace }}/dist/"
          cp "${{ github.workspace }}/scripts/steam_appid.txt" "${{ github.workspace }}/dist/"
          cp "${{ github.workspace }}/scripts/linux/xsbinit.config" "${{ github.workspace }}/dist/"

      - name: Configure CMake
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
        run: cmake -G "Ninja Multi-Config" -S "${{ github.workspace }}/source" -B "${{ github.workspace }}/cmake-build" -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/dist" -DCMAKE_TOOLCHAIN_FILE="${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-linux -DCMAKE_VERBOSE_MAKEFILE=YES -DBUILD_TESTING=YES -DSTAR_USE_JEMALLOC=OFF -DSTAR_BUILD_QT_TOOLS=OFF -DSTAR_ENABLE_STEAM_INTEGRATION=ON -DSTAR_ENABLE_DISCORD_INTEGRATION=OFF -DCMAKE_INCLUDE_PATH="${{ github.workspace }}/lib/linux/include" -DCMAKE_LIBRARY_PATH="${{ github.workspace }}/lib/linux"

      - name: Build Debug
        run: cmake --build "${{ github.workspace }}/cmake-build" --config "Debug" --parallel

      - name: Run Unit Tests
        run: ctest --test-dir "${{ github.workspace }}/cmake-build" --verbose --build-config "Debug"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64-debug
          path: dist/*

  linux-release:
    name: Linux x86_64 Release
    runs-on: ubuntu-latest

    steps:
      - name: Install Build Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev ninja-build

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Copy Auxiliary Files
        run: |
          mkdir "${{ github.workspace }}/dist"
          cp "${{ github.workspace }}/lib/linux/libsteam_api.so" "${{ github.workspace }}/dist/"
          cp "${{ github.workspace }}/scripts/steam_appid.txt" "${{ github.workspace }}/dist/"
          cp "${{ github.workspace }}/scripts/linux/xsbinit.config" "${{ github.workspace }}/dist/"

      - name: Configure CMake
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
        run: cmake -G "Ninja Multi-Config" -S "${{ github.workspace }}/source" -B "${{ github.workspace }}/cmake-build" -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/dist" -DCMAKE_TOOLCHAIN_FILE="${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-linux -DCMAKE_VERBOSE_MAKEFILE=YES -DBUILD_TESTING=NO -DSTAR_USE_JEMALLOC=OFF -DSTAR_BUILD_QT_TOOLS=OFF -DSTAR_ENABLE_STEAM_INTEGRATION=ON -DSTAR_ENABLE_DISCORD_INTEGRATION=OFF -DCMAKE_INCLUDE_PATH="${{ github.workspace }}/lib/linux/include" -DCMAKE_LIBRARY_PATH="${{ github.workspace }}/lib/linux"

      - name: Build Release
        run: cmake --build "${{ github.workspace }}/cmake-build" --config "Release" --parallel

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64-release
          path: dist/*
