name: Windows Build Check (x64)

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  build-debug:
    name: Debug Build (with Tests)
    runs-on: windows-latest

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Copy pre-built DLLs
        run: |
          mkdir "${{ github.workspace }}\dist"
          copy "${{ github.workspace }}\scripts\steam_appid.txt" "${{ github.workspace }}\dist\"
          copy "${{ github.workspace }}\scripts\windows\xsbinit.config" "${{ github.workspace }}\dist\"

      - name: Configure CMake
        run: cmake -G "Visual Studio 17 2022" -A "X64" -S "${{ github.workspace }}/source" -B "${{ github.workspace }}/cmake-build" -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/dist" -DCMAKE_TOOLCHAIN_FILE="${Env:VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreadedDebugDLL" -DCMAKE_VERBOSE_MAKEFILE=YES -DBUILD_TESTING=YES -DSTAR_USE_JEMALLOC=OFF -DSTAR_BUILD_QT_TOOLS=OFF -DSTAR_ENABLE_STEAM_INTEGRATION=ON -DSTAR_ENABLE_DISCORD_INTEGRATION=ON -DCMAKE_INCLUDE_PATH="${{ github.workspace }}\lib\windows\include" -DCMAKE_LIBRARY_PATH="${{ github.workspace }}\lib\windows"

      - name: Build Debug
        run: cmake --build "${{ github.workspace }}/cmake-build" --config "Debug" --parallel

      - name: Run Unit Tests
        run: ctest --test-dir "${{ github.workspace }}/cmake-build" --verbose --build-config "Debug"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-debug
          path: dist/*

  build-release:
    name: Release Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Copy pre-built DLLs
        run: |
          mkdir "${{ github.workspace }}\dist"
          copy "${{ github.workspace }}\scripts\steam_appid.txt" "${{ github.workspace }}\dist\"
          copy "${{ github.workspace }}\lib\windows\*.dll" "${{ github.workspace }}\dist\"
          copy "${{ github.workspace }}\scripts\windows\xsbinit.config" "${{ github.workspace }}\dist\"

      - name: Configure CMake
        run: cmake -G "Visual Studio 17 2022" -A "X64" -S "${{ github.workspace }}/source" -B "${{ github.workspace }}/cmake-build" -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/dist" -DCMAKE_TOOLCHAIN_FILE="${Env:VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreadedDLL" -DCMAKE_VERBOSE_MAKEFILE=YES -DSTAR_USE_JEMALLOC=OFF -DSTAR_BUILD_QT_TOOLS=OFF -DSTAR_ENABLE_STEAM_INTEGRATION=ON -DSTAR_ENABLE_DISCORD_INTEGRATION=ON -DCMAKE_INCLUDE_PATH="${{ github.workspace }}\lib\windows\include" -DCMAKE_LIBRARY_PATH="${{ github.workspace }}\lib\windows"

      - name: Build Release
        run: cmake --build "${{ github.workspace }}/cmake-build" --config "Release" --parallel

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-debug
          path: dist/*
